### ISSUE TITLE
PRs and issues - submit here or on main djaneiro repo?

### ISSUE THREAD

**Issue by andybak** [brmc/pycharm-djaneiro#1]
I've got some thoughts about tweaks to the generated code. If I get something accepted to the main djaneiro repo will it eventually make it's way here? Or are you prepared to diverge and it would be quicker for me to submit it to you?

**Comment by brmc** [comment]
I'm all open to ideas. The main repo hasn't really been updated in a while.
So I'm not opposed to diverging. I'm also considering writing the templates
in some intermediate format that can be compiled too both jetbrains and
sublime text formats. Or maybe just convert between formats. I'm not sure.

The next update is going to include missing model and form fields in
addition to postgres fields and form widgets. I've also got some meta
templates to help write templates directly.

What kind of tweaks are you thinking?  I know there's definitely some
things that aren't quite right.

So to answer your question, I'm not sure where you should commit. But I
plan to update this regularly. I can't speak for the main djaneiro team.

**Comment by andybak** [comment]
>  I'm also considering writing the templates
in some intermediate format that can be compiled too both jetbrains and
sublime text formats. 

This is a great idea. Using XML attributes to store multiline HTML snippets is pretty horrific!

> What kind of tweaks are you thinking? 

I haven't had a good look through but I noticed a few strange things and out-of-date idioms.

Maybe this is a more contentious issue but the abbreviations are a bit strange sometimes. They are both moderately long and hard to rememember. They should either be shorter as people will have to memorize them or longer and less obscure - bearing in mind we can rely on autocomplete in PyCharm.

**Comment by brmc** [comment]
I agree. When I created the plugin I just dumped everything that was
created two years ago into it and even then there were some issues and
peculiarities.

The naming scheme is definitely annoyingly irregular. What do you think
about both abbreviated and verbose forms for the longer fields names?

But I'd leave in the poorly named abbreviations for people who are already
accustomed to them

**Comment by brmc** [comment]
@andybak i've got a rough transpiler working in the [compiler branch](https://github.com/brmc/pycharm-djaneiro/tree/compiler). care to take a look?
