### ISSUE TITLE
Not working in Templates

### ISSUE THREAD

**Issue by joaoferrao** [brmc/pycharm-djaneiro#3]
I had this working perfectly but after a fresh install of PyCharm it seems it no longer works on .html documents.

Any thoughts on troubleshooting?

**Comment by joaoferrao** [comment]
Please ignore this issue. I ignore the fact that, for some reason, the Live Templates for Djaneiro Templates isn't associated with any files (HTML) by default.

I solved this by going into PyCharm --> Settings --> Searched for "live template" and edited the Djaneiro Templates by associating the most commonly used by me with HTML.

**Comment by brmc** [comment]
The default context for templates is "Django" so if you don't have pycharm professional, it wouldnt work. I'll add that work around to the docs though
