### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by patrickReiis** [brmc/pycharm-djaneiro#7]
I use Pycharm community and I installed this plugin through Pycharm plugins, and I restated the IDE as asked and it didn't work as well

**Comment by brmc** [comment]
Hrm...it should work in all jetbrains IDEs, including the pycharm community edition. the only thing that requires a django-specific context are the live templates for django's templating language, and that can be manually changed after installation

can you elaborate on what exactly you're doing?

**Comment by patrickReiis** [comment]
I thought I wasn't working because a functionality didn't existed but that functionality did not have to do with pycharm-djaneiro. Sorry for letting this issue open for so long.
